<a href="https://colab.research.google.com/github/mahnoor173/Data-Science-BWF-Mahnoor/blob/main/Task15/Task15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Advanced NumPy Operations**

In [1]:
import numpy as np

# Reshape
# Create a 1D array
array_1d = np.arange(12)

# Reshape to a 3x4 array
array_2d = array_1d.reshape(3, 4)
print("Reshaped 1D array to 2D array (3x4):\n", array_2d)

# Concatenate
# Create two 2D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Concatenate along rows (axis=0)
concatenated_array = np.concatenate((array1, array2), axis=0)
print("Concatenated along rows:\n", concatenated_array)

# Concatenate along columns (axis=1)
concatenated_array = np.concatenate((array1, array2), axis=1)
print("Concatenated along columns:\n", concatenated_array)

# Splitting
# Create a 2D array
array = np.arange(16).reshape(4, 4)

# Split the array into 2 sub-arrays along rows
split_array = np.split(array, 2, axis=0)
print("Array split along rows:\n", split_array)

# Split the array into 2 sub-arrays along columns
split_array = np.split(array, 2, axis=1)
print("Array split along columns:\n", split_array)

# Horizontal and Vertical Splitting
# Horizontal split
hsplit_array = np.hsplit(array, 2)
print("Horizontal split:\n", hsplit_array)

# Vertical split
vsplit_array = np.vsplit(array, 2)
print("Vertical split:\n", vsplit_array)


Reshaped 1D array to 2D array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Concatenated along rows:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along columns:
 [[1 2 5 6]
 [3 4 7 8]]
Array split along rows:
 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
Array split along columns:
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
Horizontal split:
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
Vertical split:
 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
